Prototype is new Error()
Error: Prototype is new Error()
   at testErrorStack (ErrorPrototype.js:21:9)
   at testErrorPrototype (ErrorPrototype.js:34:5)
   at testErrorPrototypeChain (ErrorPrototype.js:41:5)
   at runtest (ErrorPrototype.js:46:5)
   at Global code (ErrorPrototype.js:62:1)

Prototype has new Error()
Error: Prototype has new Error()
   at testErrorStack (ErrorPrototype.js:21:9)
   at testErrorPrototype (ErrorPrototype.js:34:5)
   at testErrorPrototypeChain (ErrorPrototype.js:42:5)
   at runtest (ErrorPrototype.js:46:5)
   at Global code (ErrorPrototype.js:62:1)

Prototype is Error.prototype
undefined

Prototype has Error.prototype
undefined

Prototype is new RangeError()
RangeError: Prototype is new RangeError()
   at testErrorStack (ErrorPrototype.js:21:9)
   at testErrorPrototype (ErrorPrototype.js:34:5)
   at testErrorPrototypeChain (ErrorPrototype.js:41:5)
   at runtest (ErrorPrototype.js:48:5)
   at Global code (ErrorPrototype.js:62:1)

Prototype has new RangeError()
RangeError: Prototype has new RangeError()
   at testErrorStack (ErrorPrototype.js:21:9)
   at testErrorPrototype (ErrorPrototype.js:34:5)
   at testErrorPrototypeChain (ErrorPrototype.js:42:5)
   at runtest (ErrorPrototype.js:48:5)
   at Global code (ErrorPrototype.js:62:1)

Prototype is RangeError.prototype
undefined

Prototype has RangeError.prototype
undefined

Prototype is 123
undefined

Prototype has 123
undefined

Prototype is new String()
undefined

Prototype has new String()
undefined

throw Error.prototype
undefined

throw RangeError.prototype
undefined

throw TypeError.prototype
undefined

